---
title: 編譯器錯誤 CS1015
ms.date: 07/20/2015
f1_keywords:
- CS1015
helpviewer_keywords:
- CS1015
ms.assetid: 53179feb-e8be-41e0-bb0b-f7879e9fa613
ms.openlocfilehash: d7c1e5071dcf7df45580714c010bd734a5d2980b
ms.sourcegitcommit: 7588136e355e10cbc2582f389c90c127363c02a5
ms.translationtype: MT
ms.contentlocale: zh-TW
ms.lasthandoff: 03/12/2020
ms.locfileid: "79171582"
---
# <a name="compiler-error-cs1015"></a><span data-ttu-id="d6452-102">編譯器錯誤 CS1015</span><span class="sxs-lookup"><span data-stu-id="d6452-102">Compiler Error CS1015</span></span>
<span data-ttu-id="d6452-103">必須是物件、字串或類別類型。</span><span class="sxs-lookup"><span data-stu-id="d6452-103">An object, string, or class type expected</span></span>  
  
 <span data-ttu-id="d6452-104">已嘗試將預先定義的資料類型傳遞到 [catch](../language-reference/keywords/try-catch.md) 區塊。</span><span class="sxs-lookup"><span data-stu-id="d6452-104">An attempt was made to pass a predefined data type into a [catch](../language-reference/keywords/try-catch.md) block.</span></span> <span data-ttu-id="d6452-105">只有衍生自 <xref:System.Exception?displayProperty=nameWithType> 的資料類型才能傳遞至 `catch` 區塊。</span><span class="sxs-lookup"><span data-stu-id="d6452-105">Only data types that derive from <xref:System.Exception?displayProperty=nameWithType> can be passed into a `catch` block.</span></span> <span data-ttu-id="d6452-106">有關異常的詳細資訊，請參閱[異常和異常處理](../programming-guide/exceptions/index.md)。</span><span class="sxs-lookup"><span data-stu-id="d6452-106">For more information on exceptions, see [Exceptions and Exception Handling](../programming-guide/exceptions/index.md).</span></span>  
  
## <a name="example"></a><span data-ttu-id="d6452-107">範例</span><span class="sxs-lookup"><span data-stu-id="d6452-107">Example</span></span>  
 <span data-ttu-id="d6452-108">下列範例會產生 CS1015：</span><span class="sxs-lookup"><span data-stu-id="d6452-108">The following sample generates CS1015:</span></span>  
  
```csharp  
// CS1015.cs  
class Sample  
{  
    static void Main()  
    {  
        try
        {  
        }  
        catch(int)   // CS1015, int is not derived from System.Exception  
        {  
        }  
    }  
}  
```
