---
title: '&#39;攔截&#39;之外不能出現&#39;再試一次&#39;陳述式'
ms.date: 07/20/2015
f1_keywords:
- bc30380
- vbc30380
helpviewer_keywords:
- BC30380
ms.assetid: 73ce950d-881f-4532-8024-40a4930abd32
ms.openlocfilehash: 346852cbd5693fbafe25413291ae284de3692875
ms.sourcegitcommit: 3d5d33f384eeba41b2dff79d096f47ccc8d8f03d
ms.translationtype: MT
ms.contentlocale: zh-TW
ms.lasthandoff: 05/04/2018
ms.locfileid: "33609154"
---
# <a name="39catch39-cannot-appear-outside-a-39try39-statement"></a>&#39;攔截&#39;之外不能出現&#39;再試一次&#39;陳述式
`Catch` 必須出現在 `Try...Catch...Finally` 陳述式區塊內。 `Catch` 區塊中有不必要的 `Try` 陳述式，或 `Catch` 陳述式出現在其對應 `Try` 區塊的範圍之外。  
  
 **錯誤識別碼：** BC30380  
  
## <a name="to-correct-this-error"></a>更正這個錯誤  
  
1.  如果 `Catch` 陳述式不是必要的，請刪除它，或放在 `Try...Catch...Finally` 陳述式區塊中。  
  
## <a name="see-also"></a>另請參閱  
 [Try...Catch...Finally 陳述式](../../visual-basic/language-reference/statements/try-catch-finally-statement.md)  
 
