---
title: '&#39;擲回&#39;陳述式不能省略之外的運算元&#39;Catch&#39;陳述式或內部&#39;Finally&#39;陳述式'
ms.date: 07/20/2015
f1_keywords:
- vbc30666
- bc30666
helpviewer_keywords:
- BC30666
ms.assetid: a208a6ea-0e36-4bf1-8984-4de1a0e38a2a
ms.openlocfilehash: e426e0d7af685fae82d8dc64a95803bdacb543e0
ms.sourcegitcommit: efff8f331fd9467f093f8ab8d23a203d6ecb5b60
ms.translationtype: MT
ms.contentlocale: zh-TW
ms.lasthandoff: 09/01/2018
ms.locfileid: "43424421"
---
# <a name="39throw39-statement-cannot-omit-operand-outside-a-39catch39-statement-or-inside-a-39finally39-statement"></a>&#39;擲回&#39;陳述式不能省略之外的運算元&#39;Catch&#39;陳述式或內部&#39;Finally&#39;陳述式
`Throw` 陳述式外的 `Catch` 陳述式必須提供例外狀況物件的名稱。  
  
 **錯誤 ID：** BC30666  
  
## <a name="to-correct-this-error"></a>更正這個錯誤  
  
1.  指定衍生自 `System.Exception`之例外狀況物件的名稱。  
  
2.  重建您的程式碼，讓 `Throw` 陳述式位於 `Catch` 區塊內。  
  
## <a name="see-also"></a>另請參閱  
 [Throw 陳述式](../../visual-basic/language-reference/statements/throw-statement.md)  
 [Try...Catch...Finally 陳述式](../../visual-basic/language-reference/statements/try-catch-finally-statement.md)  
 [在 Visual Basic 中的例外狀況類別](https://msdn.microsoft.com/library/9aac396f-34ca-4afb-8e6c-e523cb690ba9)  
 [例外狀況和 Visual Basic 中的錯誤處理](https://msdn.microsoft.com/library/3e351e73-cf23-40ab-8b60-05794160529e)
