---
title: "編譯器錯誤 CS0103 | Microsoft Docs"
ms.date: 2015-07-20
ms.prod: .net
ms.technology:
- devlang-csharp
ms.topic: error-reference
f1_keywords:
- CS0103
dev_langs:
- CSharp
helpviewer_keywords:
- CS0103
ms.assetid: fd1f2104-a945-4dba-8137-8ef869826062
caps.latest.revision: 13
author: BillWagner
ms.author: wiwagn
translation.priority.ht:
- cs-cz
- de-de
- es-es
- fr-fr
- it-it
- ja-jp
- ko-kr
- pl-pl
- pt-br
- ru-ru
- tr-tr
- zh-cn
- zh-tw
ms.translationtype: Human Translation
ms.sourcegitcommit: 400dfda51d978f35c3995f90840643aaff1b9c13
ms.openlocfilehash: cc4f086575a57c4ae56117b0852e2b8001d847f2
ms.contentlocale: zh-tw
ms.lasthandoff: 03/24/2017

---
# <a name="compiler-error-cs0103"></a>編譯器錯誤 CS0103
目前的內容中沒有名稱 'identifier'  
  
 嘗試使用類別、[命名空間](../../../csharp/language-reference/keywords/namespace.md)或範圍中沒有的名稱。 請檢查名稱的拼字，以及您的 using 指示詞和組件參考，以確定可使用您嘗試使用的名稱。  
  
 如果您在迴圈、`try` 或 `if` 區塊中宣告一個變數，然後嘗試從封閉程式碼區塊或另一個程式碼區塊存取此變數，就會時常發生這種錯誤，如下列範例所示。  
  
```csharp  
using System;  
  
class MyClass1  
{  
    public static void Main()  
    {  
        try  
        {  
            // The following declaration is only available inside the try block.  
            MyClass1 conn = new MyClass1();  
        }  
        catch (Exception e)  
        {  
            // The following expression causes error CS0103, because variable  
            // conn only exists in the try block.  
            if (conn != null)   
                Console.WriteLine("{0}", e);  
        }  
    }  
}  
```  
  
 下列範例將解決此錯誤。  
  
```csharp  
using System;  
  
class MyClass2  
{  
    public static void Main()  
    {  
        // To resolve the error in the example, the first step is to   
        // move the declaration of conn out of the try block. The following  
        // declaration is available throughout the Main method.  
        MyClass2 conn = null;  
        try  
        {  
            // Inside the try block, use the conn variable that you declared  
            // previously.  
            conn = new MyClass2();  
        }  
        catch (Exception e)  
        {  
            // The following expression no longer causes an error, because  
            // the declaration of conn is in scope.  
            if (conn != null)   
                Console.WriteLine("{0}", e);  
        }  
    }  
}  
```

