### <a name="change-in-behavior-for-taskwaitall-methods-with-time-out-arguments"></a><span data-ttu-id="b3a30-101">含逾時引數之 Task.WaitAll 方法的行為變更</span><span class="sxs-lookup"><span data-stu-id="b3a30-101">Change in behavior for Task.WaitAll methods with time-out arguments</span></span>

|   |   |
|---|---|
|<span data-ttu-id="b3a30-102">詳細資料</span><span class="sxs-lookup"><span data-stu-id="b3a30-102">Details</span></span>|<span data-ttu-id="b3a30-103">在 .NET Framework 4.5 中，<xref:System.Threading.Tasks.Task.WaitAll%2A?displayProperty=nameWithType> 行為變得更一致。在 .NET Framework 4 中，這些方法的行為不一致。</span><span class="sxs-lookup"><span data-stu-id="b3a30-103"><xref:System.Threading.Tasks.Task.WaitAll%2A?displayProperty=nameWithType> behavior was made more consistent in .NET Framework 4.5.In the .NET Framework 4, these methods behaved inconsistently.</span></span> <span data-ttu-id="b3a30-104">逾時過期時，如果在方法呼叫之前已完成或取消一個或多個工作，則方法會擲回 <xref:System.AggregateException?displayProperty=name> 例外狀況。</span><span class="sxs-lookup"><span data-stu-id="b3a30-104">When the time-out expired, if one or more tasks were completed or canceled before the method call, the method threw an <xref:System.AggregateException?displayProperty=name> exception.</span></span> <span data-ttu-id="b3a30-105">當逾時過期時，如果在方法呼叫之前沒有任何已完成或取消的工作，但是有一個或多個工作在方法呼叫之後進入這兩種狀態，則方法會傳回 false。</span><span class="sxs-lookup"><span data-stu-id="b3a30-105">When the time-out expired, if no tasks were completed or canceled before the method call, but one or more tasks entered these states after the method call, the method returned false.</span></span><br/><br/><span data-ttu-id="b3a30-106">在 .NET Framework 4.5 中，如果逾時間隔到期時仍有任何工作正在執行，這些方法多載現在會傳回 false，而只有在取消輸入工作 (不論是在方法呼叫之前或之後)，且沒有其他工作仍在執行時，才會擲回 <xref:System.AggregateException?displayProperty=name> 例外狀況。</span><span class="sxs-lookup"><span data-stu-id="b3a30-106">In the .NET Framework 4.5, these method overloads now return false if any tasks are still running when the time-out interval expired, and they throw an <xref:System.AggregateException?displayProperty=name> exception only if an input task was cancelled (regardless of whether it was before or after the method call) and no other tasks are still running.</span></span>|
|<span data-ttu-id="b3a30-107">建議</span><span class="sxs-lookup"><span data-stu-id="b3a30-107">Suggestion</span></span>|<span data-ttu-id="b3a30-108">如果透過攔截 <xref:System.AggregateException?displayProperty=name> 來偵測某個工作在叫用 <xref:System.Threading.Tasks.Task.WaitAll%2A> 呼叫之前是否已取消，該程式碼應改為透過 <xref:System.Threading.Tasks.Task.IsCanceled%2A> 屬性 (例如：.Any(t =&gt; t.IsCanceled)) 執行相同的偵測，因為 .NET Framework 4.6 只會在所有等候的工作在逾時前都已完成時，才會擲回此例外狀況。</span><span class="sxs-lookup"><span data-stu-id="b3a30-108">If an <xref:System.AggregateException?displayProperty=name> was being caught as a means of detecting a task that was cancelled prior to the <xref:System.Threading.Tasks.Task.WaitAll%2A> call being invoked, that code should instead do the same detection via the  <xref:System.Threading.Tasks.Task.IsCanceled%2A> property (for example: .Any(t =&gt; t.IsCanceled)) since .NET Framework 4.6 will only throw in that case if all awaited tasks are completed prior to the timeout.</span></span>|
|<span data-ttu-id="b3a30-109">範圍</span><span class="sxs-lookup"><span data-stu-id="b3a30-109">Scope</span></span>|<span data-ttu-id="b3a30-110">次要</span><span class="sxs-lookup"><span data-stu-id="b3a30-110">Minor</span></span>|
|<span data-ttu-id="b3a30-111">版本</span><span class="sxs-lookup"><span data-stu-id="b3a30-111">Version</span></span>|<span data-ttu-id="b3a30-112">4.5</span><span class="sxs-lookup"><span data-stu-id="b3a30-112">4.5</span></span>|
|<span data-ttu-id="b3a30-113">類型</span><span class="sxs-lookup"><span data-stu-id="b3a30-113">Type</span></span>|<span data-ttu-id="b3a30-114">執行階段</span><span class="sxs-lookup"><span data-stu-id="b3a30-114">Runtime</span></span>|
|<span data-ttu-id="b3a30-115">受影響的 API</span><span class="sxs-lookup"><span data-stu-id="b3a30-115">Affected APIs</span></span>|<ul><li><xref:System.Threading.Tasks.Task.WaitAll(System.Threading.Tasks.Task[],System.Int32)?displayProperty=nameWithType></li><li><xref:System.Threading.Tasks.Task.WaitAll(System.Threading.Tasks.Task[],System.Int32,System.Threading.CancellationToken)?displayProperty=nameWithType></li><li><xref:System.Threading.Tasks.Task.WaitAll(System.Threading.Tasks.Task[],System.TimeSpan)?displayProperty=nameWithType></li></ul>|

